name: first_seed
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs
  - annotated-types
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow-cpp>=18.0.0
  - async-timeout
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - bcrypt
  - black
  - blas=1.0=mkl
  - boost-cpp
  - bottleneck
  - brotli-python=1.0.9
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares>=1.34.4
  - ca-certificates
  - cffi=1.17.1
  - cfgv>=3.3.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - cryptography=45.0.5
  - cyrus-sasl>=2.1.28
  - datasets=3.3.2
  - deprecated=1.2.13
  - dill=0.3.8
  - distlib=0.4.0
  - distro=1.9.0
  - dnspython=2.4.2
  - ecdsa=0.19.0
  - email-validator=2.2.0
  - email_validator=2.2.0
  - exceptiongroup=1.3.0
  - expat=2.5.0
  - fastapi-cli=0.0.8
  - filelock=3.18.0
  - freetype=2.13.3
  - fsspec=2024.12.0
  - gflags=2.2.2
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - greenlet=3.1.1
  - h2=4.2.0
  - hpack=4.1.0
  - httptools=0.6.4
  - httpx-sse=0.4.0
  - huggingface_hub=0.29.2
  - hyperframe=6.1.0
  - icu>=73.1
  - identify=2.6.12
  - importlib-metadata=8.5.0
  - iniconfig=1.1.1
  - joblib=1.4.2
  - jpeg=9e
  - jsonpatch=1.33
  - krb5=1.21.3
  - lcms2=2.15
  - lerc=4.0.0
  - libjpeg-turbo>=2.1.0
  - libabseil=20250127.0
  - libboost>=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.14.1
  - libcxx=14.0.6
  - libdeflate>=1.18
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libgrpc>=1.71.0
  - libiconv>=1.17
  - libnghttp2=1.57.0
  - libopenblas=0.3.29
  - libpng>=1.6.39
  - libpq>=16.0
  - libprotobuf>=4.25.0
  - libre2-11=2024.07.02
  - libssh2>=1.11.1
  - libthrift=0.15.0
  - libtiff>=4.7.0
  - libuv=1.51.0
  - libwebp-base>=1.5.0
  - llvm-openmp=17.0.6
  - lz4-c>=1.10.0
  - markdown-it-py=3.0.0
  - mdurl=0.1.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multiprocess=0.70.15
  - mypy=1.16.0
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - networkx=3.4.2
  - nodeenv=1.9.1
  - numexpr>=2.10.0
  - numpy-base>=2.0.0
  - openjpeg>=2.5.2
  - openldap=2.6.4
  - openssl>=3.3.0
  - opentelemetry-api=1.30.0
  - orc>=2.0.0
  - passlib=1.7.4
  - pathspec=0.12.1
  - pillow>=10.0.0
  - pip=25.2
  - pluggy=1.5.0
  - pre-commit=4.2.0
  - propcache=0.3.1
  - protobuf=4.25.3
  - psutil=5.9.0
  - psycopg2=2.9.10
  - pyarrow>=18.0.0
  - pyasn1=0.6.1
  - pycparser=2.21
  - pydantic-settings=2.6.1
  - pygments=2.19.2
  - pymongo=4.13.0
  - pysocks=1.7.1
  - pytest=8.3.4
  - python=3.12.2
  - python-dateutil=2.9.0.post0
  - python-jose=3.5.0
  - python-multipart=0.0.20
  - python-tzdata=2025.2
  - python-xxhash>=3.5.0
  - pytorch>=2.4.0
  - re2=2024.07.02
  - readline=8.2
  - redis=3.5.3
  - requests-toolbelt=1.0.0
  - rich=13.9.4
  - rich-toolkit=0.14.9
  - rsa=4.7.2
  - ruff=0.12.5
  - safetensors=0.5.3
  - scikit-learn=1.7.1
  - scipy>=1.15.3
  - sentence-transformers>=4.1.0
  - setuptools=73.0.1
  - shellingham=1.5.4
  - sleef=3.5.1
  - snappy=1.2.1
  - sniffio=1.3.1
  - sqlite>=3.49.0
  - sympy=1.13.3
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tokenizers=0.21.0
  - transformers=4.49.0
  - typer=0.16.0
  - typer-slim=0.16.0
  - typer-slim-standard=0.16.0
  - typing-extensions=4.12.2
  - typing-inspection=0.4.1
  - typing_extensions=4.12.2
  - typing_inspect=0.9.0
  - ukkonen=1.0.1
  - utf8proc=2.6.1
  - uvicorn-standard=0.35.0
  - uvloop=0.21.0
  - virtualenv=20.32.0
  - watchfiles=0.24.0
  - websockets=15.0.1
  - wheel=0.45.1
  - wrapt=1.17.0
  - xxhash>=0.8.2
  - xz=5.4.6
  - yaml=0.2.5
  - zipp=3.21.0
  - zlib>=1.3.1
  - zstd=1.5.7
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - anyio==4.3.0
      - attrs==23.2.0
      - certifi==2024.2.2
      - click==8.1.7
      - dataclasses-json==0.6.4
      - et-xmlfile==1.1.0
      - faiss-cpu==1.8.0
      - fastapi==0.110.0
      - frozenlist==1.4.1
      - h11==0.14.0
      - httpcore==1.0.4
      - httpx==0.27.0
      - idna==3.6
      - jinja2==3.1.4
      - jiter==0.8.2
      - jsonpointer==2.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - langchain==0.3.27
      - langchain-community==0.3.27
      - langchain-core==0.3.72
      - langchain-deepseek==0.1.4
      - langchain-openai==0.3.28
      - langchain-text-splitters==0.3.9
      - langgraph==0.6.2
      - langgraph-checkpoint==2.1.1
      - langgraph-prebuilt==0.6.2
      - langgraph-sdk==0.2.0
      - langserve==0.3.1
      - langsmith==0.4.9
      - loguru==0.7.2
      - markupsafe==2.1.5
      - marshmallow==3.21.0
      - msgpack==1.1.0
      - multi-agents-game-framework==0.1.0
      - multidict==6.0.5
      - numpy==1.26.4
      - openai==1.98.0
      - openpyxl==3.1.2
      - orjson==3.10.12
      - ormsgpack==1.10.0
      - overrides==7.7.0
      - packaging==23.2
      - pandas==2.2.3
      - pandas-stubs==2.2.1.240316
      - pgvector==0.4.1
      - platformdirs==4.2.2
      - pydantic==2.10.3
      - pydantic-core==2.27.1
      - python-dotenv==1.0.1
      - pytz==2024.1
      - pyyaml==6.0.1
      - referencing==0.35.1
      - regex==2023.12.25
      - requests==2.31.0
      - rpds-py==0.18.1
      - six==1.16.0
      - sqlalchemy==2.0.27
      - sse-starlette==2.0.0
      - starlette==0.36.3
      - tenacity==8.2.3
      - tiktoken==0.8.0
      - tqdm==4.66.2
      - types-cffi==1.17.0.20250523
      - types-jsonschema==4.22.0.20240610
      - types-pyopenssl==24.1.0.20240722
      - types-pytz==2024.1.0.20240203
      - types-redis==4.6.0.20241004
      - types-requests==2.32.0.20240907
      - types-setuptools==80.9.0.20250529
      - tzdata==2024.1
      - urllib3==2.2.1
      - uvicorn==0.27.1
      - yarl==1.9.4
      - zstandard==0.23.0
